In [1]:
import numpy as np

In [2]:
x_data=np.array([2,4,6,8,10,12,14,16,18,20]).reshape(10,1)
t_data=np.array([0,0,0,0,0,0,1,1,1,1]).reshape(10,1)

In [3]:
x_data=np.array([[2,4],[4,11],[6,6],[8,5],[10,7],[12,16],[14,8],[16,3],[18,7]])
t_data=np.array([0,0,0,0,1,1,1,1,1]).reshape(9,1)

In [4]:
print(x_data)
print(t_data)

[[ 2  4]
 [ 4 11]
 [ 6  6]
 [ 8  5]
 [10  7]
 [12 16]
 [14  8]
 [16  3]
 [18  7]]
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [5]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w,b)

[[0.40480793]
 [0.93144338]] [0.68577127]


In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
def loss_func(x,t):
    delta=1e-7
    z=np.dot(x,w)+b
    y=sigmoid(z)
    return -np.sum(t*np.log(y+delta)+(1-t)*np.log(1-y+delta))

In [8]:
def numerical_derivative(f,x):
    delta_x= 1e-4
    grad = np.zeros_like(x)
    
#     print("debug 1. initial input variable =", x)
#     print("debug 2. initial grad =", grad)
#     print("=====================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        
#         print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_X)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
#         print("debug 4. grad[idx]=", grad[idx])
#         print("debug 5. grad =", grad)
#         print("=====================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [9]:
def predict(x):
    z=np.dot(x,w)+b
    y=sigmoid(z)
    
    if y>0.5:
        result=1
    else:
        result=0
    return y, result

In [10]:
learning_rate=1e-4

f=lambda x: loss_func(x_data, t_data)
    
print("Initial error value:", loss_func(x_data, t_data), "Initial w=",w,"Initial b=",b)

for step in range(20001):
    w-=learning_rate * numerical_derivative(f,w)
    b-=learning_rate * numerical_derivative(f,b)
    
    if step%400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=",w,"b=",b)

Initial error value: 35.033579406254674 Initial w= [[0.40480793]
 [0.93144338]] Initial b= [0.68577127]
step= 0 error value= 24.282687500565352 w= [[0.20612707]
 [0.67476443]] b= [0.64609144]
step= 400 error value= 2.2949979218531693 w= [[ 0.41759978]
 [-0.08860381]] b= [-2.58141809]
step= 800 error value= 1.599652033251949 w= [[ 0.53430275]
 [-0.02727386]] b= [-4.23641421]
step= 1200 error value= 1.2844551004074334 w= [[0.62185352]
 [0.00842758]] b= [-5.35527871]
step= 1600 error value= 1.1010137035354228 w= [[0.69244691]
 [0.03378218]] b= [-6.20978052]
step= 2000 error value= 0.9786497287042756 w= [[0.75190592]
 [0.05393441]] b= [-6.90789926]
step= 2400 error value= 0.8897409849840965 w= [[0.80343468]
 [0.0711569 ]] b= [-7.5030213]
step= 2800 error value= 0.8212700458196605 w= [[0.84898672]
 [0.08662169]] b= [-8.02527628]
step= 3200 error value= 0.7662862458535755 w= [[0.88984515]
 [0.10099511]] b= [-8.4932609]
step= 3600 error value= 0.7207293590752288 w= [[0.92690178]
 [0.11468072]

In [18]:
# (real_val, logical_val)=predict(12.96)
# print(real_val, logical_val)

In [22]:
test_data=np.array([10,2])
predict(test_data)

(array([0.37619729]), 0)