In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def numerical_derivative(f,x):
    delta_x= 1e-4
    grad = np.zeros_like(x)
    
#     print("debug 1. initial input variable =", x)
#     print("debug 2. initial grad =", grad)
#     print("=====================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        
#         print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_X)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
#         print("debug 4. grad[idx]=", grad[idx])
#         print("debug 5. grad =", grad)
#         print("=====================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [4]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name=gate_name
        self.__xdata=xdata
        self.__tdata=tdata
        
        self.__xdata=xdata.reshape(4,2)
        self.__tdata=tdata.reshape(4,1)
        
        self.__w2=np.random.rand(2,6)
        self.__b2=np.random.rand(1)
        
        self.__w3=np.random.rand(6,1)
        self.__b3=np.random.rand(1)
        
        self.__learning_rate=1e-2
        
    def feed_forward(self):
        delta=1e-7
        
        z2=np.dot(self.__xdata, self.__w2)+self.__b2
        a2=sigmoid(z2)
        
        z3=np.dot(a2, self.__w3)+self.__b3
        y=sigmoid(z3)
        
        return -np.sum(self.__tdata*np.log(y+delta)+(1-self.__tdata)*np.log((1-y)+delta))
    
    def train(self):
        f=lambda x:self.feed_forward()
        print("Initial loss func:", self.feed_forward())
        
        for step in range(10001):
            self.__w2-=self.__learning_rate*numerical_derivative(f, self.__w2)
            self.__b2-=self.__learning_rate*numerical_derivative(f, self.__b2)
            
            self.__w3-=self.__learning_rate*numerical_derivative(f, self.__w3)
            self.__b3-=self.__learning_rate*numerical_derivative(f, self.__b3)
            
            if step % 400==0:
                print("step:", step,", loss value:", self.feed_forward())
                
    def predict(self, xdata):
        z2=np.dot(xdata, self.__w2)+self.__b2
        a2=sigmoid(z2)
        
        z3=np.dot(a2, self.__w3)+self.__b3
        y=sigmoid(z3)
        
        if y>=0.5:
            result=1
        else:
            result=0
        return y, result

In [5]:
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([0,0,0,1])

and_obj=LogicGate("AND_GATE",xdata,tdata)
and_obj.train()

Initial loss func: 6.781571954730535
step: 0 , loss value: 6.5309018972881185
step: 400 , loss value: 2.2680933235850773
step: 800 , loss value: 2.1423018764161608
step: 1200 , loss value: 1.943555510362129
step: 1600 , loss value: 1.717710579853129
step: 2000 , loss value: 1.502486386859852
step: 2400 , loss value: 1.2686696785851206
step: 2800 , loss value: 1.0155020909819579
step: 3200 , loss value: 0.7800658618433916
step: 3600 , loss value: 0.5909992506212065
step: 4000 , loss value: 0.4518912157990712
step: 4400 , loss value: 0.35293455416044417
step: 4800 , loss value: 0.28253680834386075
step: 5200 , loss value: 0.23161693587091786
step: 5600 , loss value: 0.19393618441191607
step: 6000 , loss value: 0.16538038352443724
step: 6400 , loss value: 0.1432458130802291
step: 6800 , loss value: 0.1257330043793856
step: 7200 , loss value: 0.11162109497160738
step: 7600 , loss value: 0.10006399215055073
step: 8000 , loss value: 0.09046276679121554
step: 8400 , loss value: 0.082384800335

In [6]:
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00191996]), 0)
(array([0.01798773]), 0)
(array([0.01766052]), 0)
(array([0.97812793]), 1)


In [7]:
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([0,1,1,1])

or_obj=LogicGate("OR_GATE",xdata,tdata)
or_obj.train()

Initial loss func: 2.2188895243718774
step: 0 , loss value: 2.2138529887536986
step: 400 , loss value: 1.9089209114108492
step: 800 , loss value: 1.5943877785359062
step: 1200 , loss value: 1.2396197816912373
step: 1600 , loss value: 0.9270203243633206
step: 2000 , loss value: 0.6855058436527003
step: 2400 , loss value: 0.5121658134120578
step: 2800 , loss value: 0.3916409558460763
step: 3200 , loss value: 0.30783207044756633
step: 3600 , loss value: 0.24850176409784722
step: 4000 , loss value: 0.20543574270977302
step: 4400 , loss value: 0.17334256065343284
step: 4800 , loss value: 0.14882322600557635
step: 5200 , loss value: 0.1296629030517882
step: 5600 , loss value: 0.11438735718647777
step: 6000 , loss value: 0.10199213674461226
step: 6400 , loss value: 0.09177684724022306
step: 6800 , loss value: 0.0832422802758136
step: 7200 , loss value: 0.07602531523096533
step: 7600 , loss value: 0.06985685100244
step: 8000 , loss value: 0.06453404253519103
step: 8400 , loss value: 0.05990160

In [8]:
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
    print(or_obj.predict(data))

(array([0.03009582]), 0)
(array([0.99203564]), 1)
(array([0.99245047]), 1)
(array([0.99991814]), 1)


In [9]:
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([1,1,1,0])

nand_obj=LogicGate("NAND_GATE",xdata,tdata)
nand_obj.train()

Initial loss func: 4.32404490365551
step: 0 , loss value: 4.272613549512551
step: 400 , loss value: 2.2310837965892163
step: 800 , loss value: 2.0929675468281133
step: 1200 , loss value: 1.8383652844454321
step: 1600 , loss value: 1.6202652780508235
step: 2000 , loss value: 1.433007573691139
step: 2400 , loss value: 1.2383618353562487
step: 2800 , loss value: 1.0300302498810119
step: 3200 , loss value: 0.8278528127445685
step: 3600 , loss value: 0.6549032734360445
step: 4000 , loss value: 0.5198118389531454
step: 4400 , loss value: 0.4187808922705537
step: 4800 , loss value: 0.343936512376135
step: 5200 , loss value: 0.2879994710355558
step: 5600 , loss value: 0.24548492455167553
step: 6000 , loss value: 0.21254395174527413
step: 6400 , loss value: 0.18652895788089924
step: 6800 , loss value: 0.16561439501608366
step: 7200 , loss value: 0.14852603223028243
step: 7600 , loss value: 0.1343598574910273
step: 8000 , loss value: 0.12246317836035675
step: 8400 , loss value: 0.112356486901868

In [10]:
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.99656249]), 1)
(array([0.98171725]), 1)
(array([0.98171285]), 1)
(array([0.04254368]), 0)


In [11]:
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([0,1,1,0])

xor_obj=LogicGate("XOR_GATE",xdata,tdata)
xor_obj.train()

Initial loss func: 6.175264117920198
step: 0 , loss value: 6.0435895078680915
step: 400 , loss value: 2.7717036501479866
step: 800 , loss value: 2.770552647704486
step: 1200 , loss value: 2.7692245290917286
step: 1600 , loss value: 2.767534749132144
step: 2000 , loss value: 2.765244002329541
step: 2400 , loss value: 2.7620107425556704
step: 2800 , loss value: 2.75733076916758
step: 3200 , loss value: 2.7504671020286957
step: 3600 , loss value: 2.7403908209481638
step: 4000 , loss value: 2.7257713407304895
step: 4400 , loss value: 2.705034924522495
step: 4800 , loss value: 2.676424035656629
step: 5200 , loss value: 2.6379394250637977
step: 5600 , loss value: 2.5872035015516404
step: 6000 , loss value: 2.521507188253608
step: 6400 , loss value: 2.4381893926928804
step: 6800 , loss value: 2.3350803509588958
step: 7200 , loss value: 2.2106745030731965
step: 7600 , loss value: 2.064253698702043
step: 8000 , loss value: 1.896471044434135
step: 8400 , loss value: 1.7103122838183358
step: 8800

In [13]:
test_data=np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.13034435]), 0)
(array([0.80130927]), 1)
(array([0.79923095]), 1)
(array([0.29132917]), 0)
