In [1]:
import numpy as np

In [2]:
load_data = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [3]:
load_data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [4]:
x_data = load_data[:,:-1]
t_data = load_data[:,[-1]]
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [14]:
w = np.random.rand(3,1) # 3x1행렬
b = np.random.rand(1)
print(w,b)

[[0.8384711]
 [0.3106245]
 [0.0502456]] [0.23982099]


In [12]:
def loss_func(x,t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/len(x)

In [7]:
def numerical_derivative(f,x):
    delta_x= 1e-4
    grad = np.zeros_like(x)
    
#     print("debug 1. initial input variable =", x)
#     print("debug 2. initial grad =", grad)
#     print("=====================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        
#         print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_X)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
#         print("debug 4. grad[idx]=", grad[idx])
#         print("debug 5. grad =", grad)
#         print("=====================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [8]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [15]:
learning_rate=1e-6

f=lambda x: loss_func(x_data, t_data)
    
print("Initial error value:", loss_func(x_data, t_data), "Initial w=",w,"Initial b=",b)

for step in range(100001):
    w-=learning_rate * numerical_derivative(f,w)
    b-=learning_rate * numerical_derivative(f,b)
    
    if step%400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=",w,"b=",b)

Initial error value: 4566.970211858205 Initial w= [[0.8384711]
 [0.3106245]
 [0.0502456]] Initial b= [0.23982099]
step= 0 error value= 4217.917391686866 w= [[0.84922073]
 [0.32144275]
 [0.06135523]] b= [0.23994925]
step= 400 error value= 24.656050429051707 w= [[1.10547501]
 [0.58290242]
 [0.34439689]] b= [0.2431162]
step= 800 error value= 24.156443492373104 w= [[1.09782059]
 [0.57901986]
 [0.35562978]] b= [0.2431392]
step= 1200 error value= 23.671378319734448 w= [[1.09024582]
 [0.57523499]
 [0.36668975]] b= [0.24316086]
step= 1600 error value= 23.20040450117144 w= [[1.08274986]
 [0.57154581]
 [0.37757963]] b= [0.2431812]
step= 2000 error value= 22.743086222246433 w= [[1.07533186]
 [0.56795034]
 [0.38830217]] b= [0.24320025]
step= 2400 error value= 22.29900177664043 w= [[1.067991  ]
 [0.56444667]
 [0.39886007]] b= [0.24321803]
step= 2800 error value= 21.867743095378565 w= [[1.06072644]
 [0.56103287]
 [0.40925599]] b= [0.24323455]
step= 3200 error value= 21.448915292064658 w= [[1.0535373